### ISSUE TITLE
[BUG] handle Actions in forked repos

### ISSUE THREAD

**Issue by PluggPreagar** [internet4refugees/beherbergung#101]
**Describe the bug**
My forked repo can't deal with action from i4r

**Expected behavior**
just no error in github/actions on forks ;-)

**To Reproduce**
1. Go to forked github
2. Click on action
3. Choose yarn
4. run action
5. See error in action log (click on failed run)

**Environment**
github

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2373524/159879290-835e975b-5179-4339-bc3e-dd5b39e49eda.png)

**Workaround**
-- incomplete --
- added project secret GH_TOKEN_FOR_UPDATES with dummy value

**Urgency**
medium priorit`

**Comment by johannesloetzsch** [comment]
@Mic92 you have an Idea how to solve it?
Maybe we evaluate if `GH_TOKEN_FOR_UPDATES` is set and handle it more graceful if not?

**Comment by PluggPreagar** [comment]
HINT: further check your personal profile - you must have a valid PAT (personal Profile > Settings > Developer settings > Personal access tokens >> with repo-features enabled  - see https://github.com/actions/checkout#Checkout-multiple-repos-private). Those token must be set in your REPO (Repo-Profile > Settings > Secrets > Actions >> define a Secret GH_TOKEN_FOR_UPDATES and assign then PAT-Value). So the Action can make use of PAT via Repo-Secret.

**Comment by Mic92** [comment]
With my fix this should be no longer necessary, no?
