### ISSUE TITLE
[BUG] frontend: starting page raises: Maximum update depth exceeded

### ISSUE THREAD

**Issue by PluggPreagar** [internet4refugees/beherbergung#43]
Calling http://localhost:3000/ I got the page loaded. (Windows using login_max_mueller )

Still it raises  
>Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either >doesn't have a dependency array, or one of the dependencies changes on every render.
>Login@webpack-internal:///./components/Login.tsx:90:74
>div
>....

![grafik](https://user-images.githubusercontent.com/2373524/159112444-3e3584eb-a7d1-4a04-be2a-d41004148801.png)

...\backend>..\..\lein run
{:import-limit nil, :admin-passphrase *, :admin-gpg-id 9EA68B7F21204979645182E4287B083353C3241C, :db-seed src/beherbergung/db/seed/test.edn, :verbose true, :port 4000, :import-file nil, :jwt-secret *, :frontend-backend-base-url http://localhost:4000, :mail-pass *, :db-validate true, :import-ngo warhelp, :frontend-base-url http://localhost:4000, :db-dir ./data/xtdb/rocksdb, :validate-output true, :db-inmemory false, :db-export-prefix ./data/export/}
Export database to: ./data/export/20220319_083758_start.edn
Seed the database from: src/beherbergung/db/seed/test.edn
Start server at http://localhost:4000
Records to be imported: 11
nil
{:city "Dresden"}
Dresden, Sachsen, 01067, Deutschland
{:city "Leipzig"}
Leipzig, Sachsen, Deutschland
{:city "Chemnitz"}
Chemnitz, Sachsen, Deutschland
{:city "Mittweida"}
Mittweida, Mittelsachsen, Sachsen, 09648, Deutschland
{:city "Freiberg"}
Freiberg, Mittelsachsen, Sachsen, 09599, Deutschland
{:city "Radeberg"}
Radeberg, Bautzen, Sachsen, 01454, Deutschland
{:city "Radebeul"}
Radebeul, Mei├ƒen, Sachsen, 01445, Deutschland
{:city "Mei├ƒen"}
Mei├ƒen, Sachsen, Deutschland
{:city "Pirna"}
Pirna, S├ñchsische Schweiz-Osterzgebirge, Sachsen, 01796, Deutschland
{:city "Freital"}
Freital, S├ñchsische Schweiz-Osterzgebirge, Sachsen, 01705, Deutschland
import finished :)

/graphql
("accept" "accept-encoding" "accept-language" "access-control-request-headers" "access-control-request-method" "connection" "host" "origin" "referer" "sec-fetch-dest" "sec-fetch-mode" "sec-fetch-site" "user-agent")
{}
200 {"Access-Control-Allow-Methods" "DELETE, GET, POST, PUT", "Access-Control-Allow-Origin" "http://localhost:3000", "Access-Control-Allow-Headers" "Content-Type"}

/graphql
("accept" "accept-encoding" "accept-language" "connection" "content-length" "content-type" "host" "origin" "referer" "sec-fetch-dest" "sec-fetch-mode" "sec-fetch-site" "user-agent")
{}
200 {"Content-Type" "application/json; charset=utf-8", "Access-Control-Allow-Methods" "DELETE, GET, POST, PUT", "Access-Control-Allow-Origin" "http://localhost:3000"}

**Comment by johannesloetzsch** [comment]
@PluggPreagar das sollte es gelöst haben. Kannst du bitte nochmal testen?

**Comment by johannesloetzsch** [comment]
Nein, ist gerade nochmal bei mir aufgetreten :/

Muss ich später nochmal debuggen. Vielleicht hat auch @bastiion eine Idee?

**Comment by johannesloetzsch** [comment]
Scheint immer dann aufzutreten, wenn man noch nicht eingeloggt ist.
