### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Sabsifull** [internet4refugees/beherbergung#60]
**Problem**
WHAT would you like to solve / accomplish / optimize?

**Suggested solution**
You already have an idea HOW to solve it?

**Alternatives you've considered**

**Workaround**
Before the feature is implemented, can you achieve your aim another way?

**Urgency**
How quick is this feature required? What is the priority of implementing it compared to other issues?
Feel free, to assign one of this labels: `low priority`, `medium priority`, `high priority`, `urgent`

**Comment by johannesloetzsch** [comment]
Since it was only a test and contains no real issue, I close it
