### ISSUE TITLE
[Feature] Highlight free offers

### ISSUE THREAD

**Issue by Sabsifull** [internet4refugees/beherbergung#61]
**Problem**
When the Host is tagged 'occupied' then change the color on the map to 'yellow' or 'Gray'. It will be good to see on first gasp where are the housings free.

**Workaround**
Such a behavior is already **possible, with filtering by „occupied“**. To do so, uncheck the checkbox in the header of the column „occupied“.

**Comment by johannesloetzsch** [comment]
Hier 2 screenshots, die das aktuelle Verhalten zeigen:
https://github.com/internet4refugees/beherbergung/blob/main/docs/user-guide/graphics/only-unoccupied.png
https://github.com/internet4refugees/beherbergung/blob/main/docs/user-guide/graphics/only-occupied.png
Die müssen noch im user-guide eingebunden und erklärt werden…
