### ISSUE TITLE
[BUG] fullstack build does not serve frontend on / yet

### ISSUE THREAD

**Issue by Mic92** [internet4refugees/beherbergung#73]
Since https://github.com/internet4refugees/beherbergung/pull/72 there is a jar build that also contains the frontend assets but those are not yet at the right location.

**Comment by Mic92** [comment]
```
nix build .\#packages.x86_64-linux.beherbergung-fullstack -L
./result/bin/beherbergung-backend
# open http://localhost:4000 in the browser
```

**Comment by johannesloetzsch** [comment]
I think it's an issue of the `patchPublic` input provided to the derivation building the backend/fullstack derivation.

To build the `assets` / `staticHtml` of a next app,  this works fine: https://github.com/johannesloetzsch/swlkup/blob/master/frontend/nix/swlkup-frontend.nix#L24

```sh
npm run build
npm run export
```
The output will be in `./out`.

@Mic92 What you do in https://github.com/internet4refugees/beherbergung/blob/main/frontend/search/default.nix#L27 I don't understand.


I could fix it by using the frontend-derivation from `swlkup` or we could use at least it's `buildPhase` and `installPhase`?

**Comment by johannesloetzsch** [comment]
Mit dem fix aus dem Branch funkioniert:

`nix run ..#beherbergung-fullstack` wenn es aus dem `./backend` Verzeichnis gestartet wird.

Für ein staging system sollte `DB_INMEMORY=true` gesetzt werden.

http://localhost:4000/ kann mit dem Login aus ./backend/src/beherbergung/db/seed/test.edn verwendet werden :)

**Comment by Mic92** [comment]
hopefully fixed in https://github.com/internet4refugees/beherbergung/pull/88
will test.

**Comment by Mic92** [comment]
works.
