### ISSUE TITLE
[BUG] can't resolve MarkerCluster.css

### ISSUE THREAD

**Issue by PluggPreagar** [internet4refugees/beherbergung#91]
Getting error "Module not found .. MarkerCluster.css" after starting search frontend (commit ef735e4246cb6a3044e0a1efaa5527121812c85c)

**Expected**
"event - compiled client and server successfully in 1210 ms (182 modules)" message

**To Reproduce**
1. checkout ef735e4246cb6a3044e0a1efaa5527121812c85c (23.3.)
2. cd frontend/search
3. npm run dev

**Environment**
Checked on Windows

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2373524/159783186-4cf6967a-7729-4717-9369-6c51db85b169.png)

**Workaround**
While the bug in present, is there a way to work around it? - not yet -

**Urgency**
medium priority

**Comment by PluggPreagar** [comment]
merged in main by 20.3. 20:30 with 8abe19c99ccba4e64d897fcda91a1b0eeedccb45 Merge pull request #67 from internet4refugees/feature/marker-cluster

**Comment by johannesloetzsch** [comment]
@PluggPreagar please try to run `yarn` to update/install the missing dependencies

**Comment by PluggPreagar** [comment]
yarn and quit a bit install-time works out. Thanks
