### ISSUE TITLE
[BUG] Non-Uniq Modules customCircleMarker and CustomCircleMarker

### ISSUE THREAD

**Issue by PluggPreagar** [internet4refugees/beherbergung#92]
**Describe the bug**
There are multiple modules with names that only differ in casing - ./components/leaflet/marker/CustomCircleMarker.tsx - Windows-Env ;-)

frontend\search\components\leaflet\marker\CustomCircleMarker.tsx
frontend\search\components\leaflet\marker\customCircleMarker.tsx

**Expected behavior**
clear usage of cases - no error in windows

**To Reproduce**
1. checkout ef735e4246cb6a3044e0a1efaa5527121812c85c (23.3.)
2. cd frontend/search
3. npm run dev
4. open http://localhost:3000/
5. See error

**Environment**
Windows

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2373524/159791279-e702b1ac-482b-4934-a170-ff85a1a78d36.png)

**Workaround**
not yet

**Urgency**
medium priority

**Comment by johannesloetzsch** [comment]
@PluggPreagar  would you like to fix it and create a pull request to @bastiion?

**Comment by PluggPreagar** [comment]
handed over - see #99

**Comment by bastiion** [comment]
fixed by #99
